import { Article, HskLevel } from '../types';

const MOCK_ARTICLES: Article[] = [
  {
    title: '我的一天',
    title_pinyin: 'Wǒ de yī tiān',
    title_english: 'My Day',
    hsk_level: 2,
    topic: 'Daily life',
    sentences: [
      {
        chinese: '我每天早上七点起床。',
        pinyin: 'Wǒ měi tiān zǎo shang qī diǎn qǐ chuáng.',
        english: 'I get up at seven o\'clock every morning.',
        words: [
          { chinese: '我', pinyin: 'wǒ', english: 'I / me' },
          { chinese: '每天', pinyin: 'měi tiān', english: 'every day' },
          { chinese: '早上', pinyin: 'zǎo shang', english: 'morning' },
          { chinese: '七点', pinyin: 'qī diǎn', english: 'seven o\'clock' },
          { chinese: '起床', pinyin: 'qǐ chuáng', english: 'get out of bed' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '我先洗脸，然后吃早饭。',
        pinyin: 'Wǒ xiān xǐ liǎn, rán hòu chī zǎo fàn.',
        english: 'First I wash my face, then I eat breakfast.',
        words: [
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '先', pinyin: 'xiān', english: 'first' },
          { chinese: '洗脸', pinyin: 'xǐ liǎn', english: 'wash one\'s face' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '然后', pinyin: 'rán hòu', english: 'then; afterwards' },
          { chinese: '吃', pinyin: 'chī', english: 'eat' },
          { chinese: '早饭', pinyin: 'zǎo fàn', english: 'breakfast' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '早饭我喜欢吃鸡蛋和面包。',
        pinyin: 'Zǎo fàn wǒ xǐ huān chī jī dàn hé miàn bāo.',
        english: 'For breakfast I like to eat eggs and bread.',
        words: [
          { chinese: '早饭', pinyin: 'zǎo fàn', english: 'breakfast' },
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '喜欢', pinyin: 'xǐ huān', english: 'like; enjoy' },
          { chinese: '吃', pinyin: 'chī', english: 'eat' },
          { chinese: '鸡蛋', pinyin: 'jī dàn', english: 'egg' },
          { chinese: '和', pinyin: 'hé', english: 'and' },
          { chinese: '面包', pinyin: 'miàn bāo', english: 'bread' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '八点半我去公司上班。',
        pinyin: 'Bā diǎn bàn wǒ qù gōng sī shàng bān.',
        english: 'At eight-thirty I go to the office for work.',
        words: [
          { chinese: '八点半', pinyin: 'bā diǎn bàn', english: 'eight-thirty' },
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '去', pinyin: 'qù', english: 'go' },
          { chinese: '公司', pinyin: 'gōng sī', english: 'company; office' },
          { chinese: '上班', pinyin: 'shàng bān', english: 'go to work' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '我坐地铁去公司，大概要三十分钟。',
        pinyin: 'Wǒ zuò dì tiě qù gōng sī, dà gài yào sān shí fēn zhōng.',
        english: 'I take the subway to the office, which takes about thirty minutes.',
        words: [
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '坐', pinyin: 'zuò', english: 'take (transport); sit' },
          { chinese: '地铁', pinyin: 'dì tiě', english: 'subway; metro' },
          { chinese: '去', pinyin: 'qù', english: 'go' },
          { chinese: '公司', pinyin: 'gōng sī', english: 'company' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '大概', pinyin: 'dà gài', english: 'approximately; about' },
          { chinese: '要', pinyin: 'yào', english: 'need; take (time)' },
          { chinese: '三十', pinyin: 'sān shí', english: 'thirty' },
          { chinese: '分钟', pinyin: 'fēn zhōng', english: 'minute(s)' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '中午我和同事一起吃午饭。',
        pinyin: 'Zhōng wǔ wǒ hé tóng shì yī qǐ chī wǔ fàn.',
        english: 'At noon I eat lunch together with my colleagues.',
        words: [
          { chinese: '中午', pinyin: 'zhōng wǔ', english: 'noon; midday' },
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '和', pinyin: 'hé', english: 'and; with' },
          { chinese: '同事', pinyin: 'tóng shì', english: 'colleague; coworker' },
          { chinese: '一起', pinyin: 'yī qǐ', english: 'together' },
          { chinese: '吃', pinyin: 'chī', english: 'eat' },
          { chinese: '午饭', pinyin: 'wǔ fàn', english: 'lunch' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '我们公司附近有很多餐厅。',
        pinyin: 'Wǒ men gōng sī fù jìn yǒu hěn duō cān tīng.',
        english: 'Near our office there are many restaurants.',
        words: [
          { chinese: '我们', pinyin: 'wǒ men', english: 'we; our' },
          { chinese: '公司', pinyin: 'gōng sī', english: 'company' },
          { chinese: '附近', pinyin: 'fù jìn', english: 'nearby; in the vicinity' },
          { chinese: '有', pinyin: 'yǒu', english: 'have; there is/are' },
          { chinese: '很多', pinyin: 'hěn duō', english: 'many; a lot of' },
          { chinese: '餐厅', pinyin: 'cān tīng', english: 'restaurant' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '下午我在办公室工作，有时候开会。',
        pinyin: 'Xià wǔ wǒ zài bàn gōng shì gōng zuò, yǒu shí hòu kāi huì.',
        english: 'In the afternoon I work in the office, and sometimes have meetings.',
        words: [
          { chinese: '下午', pinyin: 'xià wǔ', english: 'afternoon' },
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '在', pinyin: 'zài', english: 'at; in' },
          { chinese: '办公室', pinyin: 'bàn gōng shì', english: 'office' },
          { chinese: '工作', pinyin: 'gōng zuò', english: 'work' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '有时候', pinyin: 'yǒu shí hòu', english: 'sometimes' },
          { chinese: '开会', pinyin: 'kāi huì', english: 'hold / attend a meeting' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '晚上六点我下班回家。',
        pinyin: 'Wǎn shàng liù diǎn wǒ xià bān huí jiā.',
        english: 'At six in the evening I finish work and go home.',
        words: [
          { chinese: '晚上', pinyin: 'wǎn shàng', english: 'evening; night' },
          { chinese: '六点', pinyin: 'liù diǎn', english: 'six o\'clock' },
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '下班', pinyin: 'xià bān', english: 'finish work; get off work' },
          { chinese: '回家', pinyin: 'huí jiā', english: 'go home' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '回家以后，我做饭、看书，然后睡觉。',
        pinyin: 'Huí jiā yǐ hòu, wǒ zuò fàn, kàn shū, rán hòu shuì jiào.',
        english: 'After getting home, I cook, read, and then sleep.',
        words: [
          { chinese: '回家', pinyin: 'huí jiā', english: 'go home' },
          { chinese: '以后', pinyin: 'yǐ hòu', english: 'after; afterwards' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '做饭', pinyin: 'zuò fàn', english: 'cook; make food' },
          { chinese: '、', pinyin: '', english: '' },
          { chinese: '看书', pinyin: 'kàn shū', english: 'read (a book)' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '然后', pinyin: 'rán hòu', english: 'then; afterwards' },
          { chinese: '睡觉', pinyin: 'shuì jiào', english: 'sleep; go to sleep' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
    ],
    vocabulary: [
      {
        word: '起床',
        pinyin: 'qǐ chuáng',
        definition: 'to get out of bed; to get up',
        hsk_level: 2,
      },
      {
        word: '附近',
        pinyin: 'fù jìn',
        definition: 'nearby; in the vicinity of',
        hsk_level: 3,
      },
      {
        word: '同事',
        pinyin: 'tóng shì',
        definition: 'colleague; coworker',
        hsk_level: 3,
      },
      {
        word: '开会',
        pinyin: 'kāi huì',
        definition: 'to hold or attend a meeting',
        hsk_level: 3,
      },
      {
        word: '以后',
        pinyin: 'yǐ hòu',
        definition: 'after; afterwards; later',
        hsk_level: 2,
      },
    ],
  },
  {
    title: '周末去市场',
    title_pinyin: 'Zhōu mò qù shì chǎng',
    title_english: 'Going to the Market on the Weekend',
    hsk_level: 3,
    topic: 'Food & cooking',
    sentences: [
      {
        chinese: '今天是星期六，我决定去菜市场买东西。',
        pinyin: 'Jīn tiān shì xīng qī liù, wǒ jué dìng qù cài shì chǎng mǎi dōng xi.',
        english: 'Today is Saturday, and I decided to go to the food market to buy things.',
        words: [
          { chinese: '今天', pinyin: 'jīn tiān', english: 'today' },
          { chinese: '是', pinyin: 'shì', english: 'is / am / are' },
          { chinese: '星期六', pinyin: 'xīng qī liù', english: 'Saturday' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '决定', pinyin: 'jué dìng', english: 'decide' },
          { chinese: '去', pinyin: 'qù', english: 'go' },
          { chinese: '菜市场', pinyin: 'cài shì chǎng', english: 'food market' },
          { chinese: '买', pinyin: 'mǎi', english: 'buy' },
          { chinese: '东西', pinyin: 'dōng xi', english: 'things; stuff' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '市场里人很多，非常热闹。',
        pinyin: 'Shì chǎng lǐ rén hěn duō, fēi cháng rè nào.',
        english: 'The market was very crowded and lively.',
        words: [
          { chinese: '市场', pinyin: 'shì chǎng', english: 'market' },
          { chinese: '里', pinyin: 'lǐ', english: 'inside; within' },
          { chinese: '人', pinyin: 'rén', english: 'people; person' },
          { chinese: '很多', pinyin: 'hěn duō', english: 'many; a lot' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '非常', pinyin: 'fēi cháng', english: 'very; extremely' },
          { chinese: '热闹', pinyin: 'rè nào', english: 'lively; bustling' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '我先去买蔬菜，挑了一些西红柿和黄瓜。',
        pinyin: 'Wǒ xiān qù mǎi shū cài, tiāo le yī xiē xī hóng shì hé huáng guā.',
        english: 'I first went to buy vegetables, and picked out some tomatoes and cucumbers.',
        words: [
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '先', pinyin: 'xiān', english: 'first' },
          { chinese: '去', pinyin: 'qù', english: 'go' },
          { chinese: '买', pinyin: 'mǎi', english: 'buy' },
          { chinese: '蔬菜', pinyin: 'shū cài', english: 'vegetables' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '挑', pinyin: 'tiāo', english: 'pick; select' },
          { chinese: '了', pinyin: 'le', english: 'completed action particle' },
          { chinese: '一些', pinyin: 'yī xiē', english: 'some; a few' },
          { chinese: '西红柿', pinyin: 'xī hóng shì', english: 'tomato' },
          { chinese: '和', pinyin: 'hé', english: 'and' },
          { chinese: '黄瓜', pinyin: 'huáng guā', english: 'cucumber' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '卖菜的大叔告诉我今天的西红柿特别新鲜。',
        pinyin: 'Mài cài de dà shū gào sù wǒ jīn tiān de xī hóng shì tè bié xīn xiān.',
        english: 'The vegetable seller told me that today\'s tomatoes were especially fresh.',
        words: [
          { chinese: '卖菜', pinyin: 'mài cài', english: 'sell vegetables' },
          { chinese: '的', pinyin: 'de', english: 'possessive / modifier particle' },
          { chinese: '大叔', pinyin: 'dà shū', english: 'middle-aged man; uncle' },
          { chinese: '告诉', pinyin: 'gào sù', english: 'tell; inform' },
          { chinese: '我', pinyin: 'wǒ', english: 'me' },
          { chinese: '今天', pinyin: 'jīn tiān', english: 'today' },
          { chinese: '的', pinyin: 'de', english: 'possessive particle' },
          { chinese: '西红柿', pinyin: 'xī hóng shì', english: 'tomato' },
          { chinese: '特别', pinyin: 'tè bié', english: 'especially; particularly' },
          { chinese: '新鲜', pinyin: 'xīn xiān', english: 'fresh' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '然后我去买了一条鱼和半斤猪肉。',
        pinyin: 'Rán hòu wǒ qù mǎi le yī tiáo yú hé bàn jīn zhū ròu.',
        english: 'Then I went and bought a fish and half a jin of pork.',
        words: [
          { chinese: '然后', pinyin: 'rán hòu', english: 'then; afterwards' },
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '去', pinyin: 'qù', english: 'go' },
          { chinese: '买', pinyin: 'mǎi', english: 'buy' },
          { chinese: '了', pinyin: 'le', english: 'completed action particle' },
          { chinese: '一条', pinyin: 'yī tiáo', english: 'one (fish / long things)' },
          { chinese: '鱼', pinyin: 'yú', english: 'fish' },
          { chinese: '和', pinyin: 'hé', english: 'and' },
          { chinese: '半斤', pinyin: 'bàn jīn', english: 'half a jin (≈250 g)' },
          { chinese: '猪肉', pinyin: 'zhū ròu', english: 'pork' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '水果区有很多种类，我买了苹果和香蕉。',
        pinyin: 'Shuǐ guǒ qū yǒu hěn duō zhǒng lèi, wǒ mǎi le píng guǒ hé xiāng jiāo.',
        english: 'The fruit section had many varieties; I bought apples and bananas.',
        words: [
          { chinese: '水果', pinyin: 'shuǐ guǒ', english: 'fruit' },
          { chinese: '区', pinyin: 'qū', english: 'area; section; zone' },
          { chinese: '有', pinyin: 'yǒu', english: 'have; there is/are' },
          { chinese: '很多', pinyin: 'hěn duō', english: 'many; a lot of' },
          { chinese: '种类', pinyin: 'zhǒng lèi', english: 'variety; type; kind' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '买', pinyin: 'mǎi', english: 'buy' },
          { chinese: '了', pinyin: 'le', english: 'completed action particle' },
          { chinese: '苹果', pinyin: 'píng guǒ', english: 'apple' },
          { chinese: '和', pinyin: 'hé', english: 'and' },
          { chinese: '香蕉', pinyin: 'xiāng jiāo', english: 'banana' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '最后，我在一家小店买了豆腐和酱油。',
        pinyin: 'Zuì hòu, wǒ zài yī jiā xiǎo diàn mǎi le dòu fu hé jiàng yóu.',
        english: 'Finally, I bought tofu and soy sauce at a small shop.',
        words: [
          { chinese: '最后', pinyin: 'zuì hòu', english: 'finally; last' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '在', pinyin: 'zài', english: 'at; in' },
          { chinese: '一家', pinyin: 'yī jiā', english: 'one (shop / establishment)' },
          { chinese: '小店', pinyin: 'xiǎo diàn', english: 'small shop' },
          { chinese: '买', pinyin: 'mǎi', english: 'buy' },
          { chinese: '了', pinyin: 'le', english: 'completed action particle' },
          { chinese: '豆腐', pinyin: 'dòu fu', english: 'tofu' },
          { chinese: '和', pinyin: 'hé', english: 'and' },
          { chinese: '酱油', pinyin: 'jiàng yóu', english: 'soy sauce' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '回到家以后，我开始准备晚饭。',
        pinyin: 'Huí dào jiā yǐ hòu, wǒ kāi shǐ zhǔn bèi wǎn fàn.',
        english: 'After getting home, I started preparing dinner.',
        words: [
          { chinese: '回到', pinyin: 'huí dào', english: 'return to; arrive back' },
          { chinese: '家', pinyin: 'jiā', english: 'home; family' },
          { chinese: '以后', pinyin: 'yǐ hòu', english: 'after; afterwards' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '开始', pinyin: 'kāi shǐ', english: 'start; begin' },
          { chinese: '准备', pinyin: 'zhǔn bèi', english: 'prepare; get ready' },
          { chinese: '晚饭', pinyin: 'wǎn fàn', english: 'dinner; supper' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
      {
        chinese: '我做了番茄炒蛋和清蒸鱼，味道很好。',
        pinyin: 'Wǒ zuò le fān qié chǎo dàn hé qīng zhēng yú, wèi dào hěn hǎo.',
        english: 'I made tomato and egg stir-fry and steamed fish — it tasted great.',
        words: [
          { chinese: '我', pinyin: 'wǒ', english: 'I' },
          { chinese: '做', pinyin: 'zuò', english: 'make; cook; do' },
          { chinese: '了', pinyin: 'le', english: 'completed action particle' },
          { chinese: '番茄炒蛋', pinyin: 'fān qié chǎo dàn', english: 'tomato and egg stir-fry' },
          { chinese: '和', pinyin: 'hé', english: 'and' },
          { chinese: '清蒸鱼', pinyin: 'qīng zhēng yú', english: 'steamed fish' },
          { chinese: '，', pinyin: '', english: '' },
          { chinese: '味道', pinyin: 'wèi dào', english: 'taste; flavour' },
          { chinese: '很好', pinyin: 'hěn hǎo', english: 'very good' },
          { chinese: '。', pinyin: '', english: '' },
        ],
      },
    ],
    vocabulary: [
      {
        word: '热闹',
        pinyin: 'rè nào',
        definition: 'lively; bustling; full of noise and activity',
        hsk_level: 4,
      },
      {
        word: '新鲜',
        pinyin: 'xīn xiān',
        definition: 'fresh (food); novel; new',
        hsk_level: 3,
      },
      {
        word: '种类',
        pinyin: 'zhǒng lèi',
        definition: 'kind; type; variety; category',
        hsk_level: 4,
      },
      {
        word: '清蒸',
        pinyin: 'qīng zhēng',
        definition: 'to steam (cooking method); steamed',
        hsk_level: 5,
      },
      {
        word: '准备',
        pinyin: 'zhǔn bèi',
        definition: 'to prepare; to get ready',
        hsk_level: 3,
      },
    ],
  },
];

export function getMockArticle(hskLevel: HskLevel, topic: string): Article {
  // Find the closest matching article by HSK level
  const sorted = [...MOCK_ARTICLES].sort(
    (a, b) => Math.abs(a.hsk_level - hskLevel) - Math.abs(b.hsk_level - hskLevel)
  );
  const article = sorted[0];
  // Return it with the requested level/topic stamped on it
  return { ...article, hsk_level: hskLevel, topic: topic.trim() || article.topic };
}
